name: Deploy React to Onamae Server

on:
  push:
    branches: [ "main" ]  # main ブランチに push されたらデプロイ

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy via rsync over SSH
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avz --delete
          path: build/
          remote_path: public_html/greenoffset.jp # ←ここに修正
          remote_host: ${{ secrets.WEB_SERVER }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_port: 8022
